// Public surface of the pipeline module (Stories 5.1-5.3): the job queue,
// the versioned worker contract and the job API for people.
export {
  PIPELINE_KINDS,
  PIPELINE_KIND_HEIC_TO_JPEG,
  PIPELINE_KIND_PROXY_720P,
  KIND_RE,
  isBuiltInKind,
  isKindName,
} from './kinds.ts';
export type { BuiltInKind } from './kinds.ts';
export {
  JOB_STATUSES,
  MAX_ATTEMPTS,
  OUTPUT_MIME_TYPES,
  PipelineFailure,
  RETRY_DELAY_SECONDS,
  kindAccepts,
  contractMajor,
  isTerminal,
  jobState,
  parseFail,
  parseHeartbeat,
  parseManifest,
  parseOutputHeaders,
  parseProgress,
  parseRegister,
} from './contract.ts';
export type {
  ClaimResponse,
  ClaimedJob,
  CompleteResponse,
  EmptyBody,
  ErrorBody,
  FailRequest,
  FailResponse,
  HeartbeatRequest,
  HeartbeatResponse,
  JobPathParams,
  JobState,
  JobStatus,
  Manifest,
  OutputResponse,
  PipelineErrorCode,
  ProgressRequest,
  ProgressResponse,
  RegisterRequest,
  RegisterResponse,
  ReleaseResponse,
} from './contract.ts';
export {
  FILE_TRASHED_ERROR,
  JobRequestError,
  LEASE_EXPIRED_ERROR,
  WORKER_PRUNE_DAYS,
  cancelJob,
  cancelJobsOfTrashedFiles,
  claimNext,
  completeJob,
  enqueueJob,
  failJob,
  heartbeat,
  inputResponse,
  jobById,
  jobsForFile,
  kindLabel,
  leaseSeconds,
  listWorkers,
  liveKinds,
  pipelineCounts,
  pruneWorkers,
  registerWorker,
  releaseJob,
  reportProgress,
  revokeWorker,
  storeOutput,
  sweepExpiredClaims,
} from './service.ts';
export type { JobRequestCode, JobView, WorkerView } from './service.ts';
export { pipelineErrorResponse, readJsonBody } from './http.ts';
